### ISSUE TITLE
Deploy to Netlify

### ISSUE THREAD

**Issue by jimafisk** [plentico/plenti#140]
I've had several people asking about deploying to Netlify, so I finally took a look today and was kind of surprised by what I found. I assumed you could point Netlify's CI to use whatever docker image you want (like the official Plenti image: https://hub.docker.com/r/plentico/plenti), but it looks they use a single build image to try to account for a variety of different projects: https://github.com/netlify/build-image. That's generally fine for NPM based projects, but challenging for CLI tools that ship their own binary. Apparently you can make PRs to their build image to include your project's binary, but they only accept projects if they meet certain criteria (see similar discussion here: https://community.netlify.com/t/adding-a-new-ssg-judoc-jl/3229). It's also not clear how you would manage versions this way. Since Plenti is early dev we often break backwards compatibility, but you can easily target a specific version of Plenti for your CI builds to keep things working no matter what we change (dockerhub has tags for all builds https://hub.docker.com/r/plentico/plenti/tags?page=1&ordering=last_updated).

There are some other options for a similar use case to ours discussed here: https://community.netlify.com/t/custom-static-site-generator/28578. I don't like the idea of forcing the using to bundle the Plenti source code or even a compiled binary with their project in order to build in Netlify CI - it seems like a lot of unnecessary steps that could confuse folks and slow down the end-to-end build. I know we've also talked about bundling the Plenti binary in an NPM package (https://github.com/plentico/plenti/issues/135), but I keep wavering on whether we should actually do this or not. My general preference is to rely less on NPM and the standard javascript ecosystem and I'd rather not have multiple ways to accomplish the same thing (e.g. builds with `plenti build` and `npm run build`). At best this would hang out in the background as a Netlify hack to allow builds on their limited CI infrastructure, at worst we develop fractured standards and Plenti becomes ever more embedded in javascript tooling.

A better approach is probably to build your Plenti app in CI outside of Netlify and deploy the built assets afterwards. Here's a GitHub Actions example, create a `.github/workflows/netlify-deploy.yml` file with these contents:

```
name: netlify deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Build
        uses: docker://plentico/plenti:latest
        with:
          entrypoint: /plenti
          args: build

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '13'

      - name: Deploy to Netlify
        run: |
          npm install netlify-cli -g
          netlify deploy --prod --dir ./public --site=${{ secrets.NETLIFY_SITE_ID }} --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} --timeout=600 --message "Deployed on $(date)"
```
(Deploy step is copied from https://blog.56k.cloud/deploying-static-sites-with-github-actions-and-netlify/)

**IMPORTANT:** You also need to connect your app to Netlify with the follow steps:
1. Create a personal access token on Netlify (https://app.netlify.com/user/applications#personal-access-tokens), copy this, then in your GitHub repo go to "Settings (rightmost link in nav) > Secrets (bottom of lefthand sidbar) > New Repository secret (button in top right)" and paste it as the "Value" and set the "Name" to `NETLIFY_AUTH_TOKEN`.
2. On Netlify created a placeholder site, select "Site Settings (rightmost link in nav) > General (First link if lefthand sidebar) > Site Details (First section under General)" and copy the "API ID" and then back in GitHub Secrets (same as above) paste this as the "Value" and set the "Name" to `NETLIFY_SITE_ID`.

Here's a working example:
- Plenti app on Netlify: https://dreamy-mayer-cfe1fe.netlify.app/
- Github repo: https://github.com/jimafisk/plenti_multi-pager_example

I've echoed these thoughts here as well: https://www.reddit.com/r/sveltejs/comments/l3lg6f/using_plenti_to_make_a_simple_svelte_static_site/gmsxy0i/
