### ISSUE TITLE
Can't build in GitLab: exec: "sh": executable file not found in $PATH

### ISSUE THREAD

**Issue by jimafisk** [plentico/plenti#180]
The [docs for deploying to GitLab](https://plenti.co/docs/gitlab-piplines) are no longer working with our new `scratch` container: https://github.com/plentico/plenti/issues/157#issuecomment-816915093. If you use that `.gitlab-ci.yml` you'll likely see an error like:
```
ERROR: Job failed (system failure): Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "sh": executable file not found in $PATH: unknown (exec.go:67:0s)
```

This is happening because [a scratch image doesn't have a shell](https://stackoverflow.com/questions/40211644/attaching-to-a-docker-container-with-base-image-scratch). We could change out [our default image](https://hub.docker.com/repository/docker/plentico/plenti) for an `alpine` container, but I'd prefer we keep our containers as small as possible since the whole editing workflow is based on the concept of fast cold startup builds in CI.
  
Here's a ticket in GitLab discussing adding support for `scratch` images: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/26501#note_591353331 <- this is exactly what we'd need to get this working without compromising container size. Show some love over there if you're interested in getting this resolved. Thanks!

**Comment by jimafisk** [comment]
Another related issue: https://gitlab.com/gitlab-org/gitlab/-/issues/19717

**Comment by jimafisk** [comment]
For anyone who needs a workaround in the meantime, here's an example `.gitlab-ci.yml`:
```yml
image: docker:stable

pages:
  before_script:
    - apk add --update curl wget && rm -rf /var/cache/apk/*
  script:
    - wget -c $(curl -s https://api.github.com/repos/plentico/plenti/releases/latest | grep -o 'http.*Linux_64-bit.tar.gz')
    - tar -zxvf *_Linux_64-bit.tar.gz
    - ./plenti build
  artifacts:
    paths:
      - public
  only:
    - main
```

**Comment by jimafisk** [comment]
Additionally if you want text compression to improve your performance score:

```yml
image: docker:stable

pages:
  before_script:
    - apk add --update curl wget && rm -rf /var/cache/apk/*
  script:
    - wget -c $(curl -s https://api.github.com/repos/plentico/plenti/releases/latest | grep -o 'http.*Linux_64-bit.tar.gz')
    - tar -zxvf *_Linux_64-bit.tar.gz
    - ./plenti build
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|mjs\|css\|json\)$' -exec gzip -f -k {} \;
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|mjs\|css\|json\)$' -exec brotli -f -k {} \;
  artifacts:
    paths:
      - public
  only:
    - main
```
