### ISSUE TITLE
Netlify backend for CMS 

### ISSUE THREAD

**Issue by jimafisk** [plentico/plenti#262]
We currently have a [GitLab backend](https://github.com/plentico/plenti/issues/24#issuecomment-795385661) for the CMS and would like to add a [GitHub backend](https://github.com/plentico/plenti/issues/188) as well, but that is held up until they support PKCE. Another popular option for backend provider who be Netlify since they have their own Git and OAuth.

Netlify can be used as an [OAuth provider](https://www.netlify.com/blog/2016/10/10/integrating-with-netlify-oauth2/). It sounds like they support Implicit Grant, but not sure about PKCE - we'd want to verify this before attempting to implement.

Another strange thing is Netlify's build process. You can't actually specify a custom image as [shown here](https://youtu.be/TmWIeUOsERY?t=262) and [discussed here](https://answers.netlify.com/t/can-we-use-our-dockerfile-to-build-an-image-and-deploy-it-in-netlify/26996). We'd have to get a PR accepted to their [build image](https://github.com/netlify/build-image), similar to the [Hugo setup](https://github.com/netlify/build-image/blob/focal/Dockerfile#L375) in order to build Plenti sites in their CI (otherwise you have to build elsewhere and copy the files over). Seems like a very strange approach, their Hugo build version is set manually and already many versions behind the current release.

**Comment by jamestagal** [comment]
Hi Jim,

I just wanted to follow up on this post and see whether it is worth looking further into this. I was interest in using Netlify only because they manage a nice easy solution for web forms. And I think you can even forward them on for clients.   

I had a quick look in Netlify's docs https://docs.netlify.com/security/secure-access-to-sites/oauth-provider-tokens/ 
but I didn't see any reference to PKCE auth and then their is the other complication you mentioned about their build process.

I guess this is not a very good reason to pursue Netlify as a backend for Plenti's CMS but I am just having issues implementing a simple and robust web form submission solution. 😞 

Best regards,
Ben

**Comment by jimafisk** [comment]
Hi @jamestagal,

You should be able to use Netlify as your website host if you prefer that to [GitLab Pages](https://docs.gitlab.com/ee/user/project/pages/), you'd just still need to use GitLab for your CI/CD builds and OAuth. This video has some basic instructions on how to set that up: https://youtu.be/TmWIeUOsERY?si=wWjjoYzvCRokCgIG&t=574 

**Things to note:**
- I try several failed attempts to push the assets from CI to Netflify, but ultimately decide to use the Netlify CLI directly as described here: https://youtu.be/TmWIeUOsERY?si=koC3W6Mb3FemyFuB&t=1037
- I'm using GitHub actions in the video, if you're using GitLab it would be a `.gitlab-ci.yml` file
- The `--dir` flag has been renamed to `--output` https://youtu.be/TmWIeUOsERY?si=pRRnogya9c1YWCFt&t=873

**Comment by jamestagal** [comment]
Thanks Jim.

I will take a look and see if I can set it up. 

BTW. It wouldn't be that I prefer one over the other it's just a case of getting a web form solution that just works. :)
I have been trying to get a Google Form which is connected to the site and to the clients Gmail to work and I have had mixed results and nothing that is working consistently. 

Thanks for posting here Jim.
Appreciate it.
Regards,

Ben

**Comment by jamestagal** [comment]
Hi @jimafisk 
I have a couple of follow up question:

1. Would the following be ok for a possible  build```netlify-deploy.yml``` file?

```yml
name: netlify deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        uses: docker://plentico/plenti:latest
        with:
          entrypoint: /plenti
          args: build  --output=build

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '16'

      - name: Deploy to Netlify
        run: |
          npm install netlify-cli -g
          netlify deploy --prod --dir deploy/public --site=${{ secrets.NETLIFY_SITE_ID }} --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} --timeout=600 --message "Deployed on $(date)"
```
2. So clarify the Actions for GitLab, would I just generate an access token and Site ID in Netlify and save them in a ```.gitlab-ci.yml``` file in GitLab? I'm not completely sure of this step.
Thanks Ben
