### ISSUE TITLE
Can't initialize containers containers in GitHub Actions

### ISSUE THREAD

**Issue by jimafisk** [plentico/plenti#64]
Currently having trouble using the [official plenti docker image](https://hub.docker.com/repository/docker/plentico/plenti) to build a site in CI. With GitHub Actions specifically it breaks during the "Initialize containers" step.

Failed build: https://github.com/plentico/plenti.co/runs/1038266264?check_suite_focus=true#step:2:28

Error message:
```
Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"tail\": executable file not found in $PATH": unknown
Error: failed to start containers: c548933df06aedf4dcacf3b69e774f91ea792dcad449e4e0f0dfd2e9baec6965
##[error]Docker start fail with exit code 1
```

Trying with another arbitrary image like nodejs works: https://github.com/plentico/plenti.co/runs/1038343465?check_suite_focus=true <- note the build still fails because the plenti binary isn't on the container, but the containers initialize fine.

This might be because the container is starting and immediately stopping: https://stackoverflow.com/questions/57694335/github-actions-workflow-fails-when-running-steps-in-a-container. Will try to update the `ENTRYPOINT` in the `Dockerfile`: https://github.com/plentico/plenti/blob/f1ff1f1127791910d98c61f94e277af4dc037bb2/Dockerfile#L3 to use something like `ENTRYPOINT tail -f /dev/null` as shown in [the example](https://github.com/rizwan937/Helm-Image/blob/master/Dockerfile#L12).

**Comment by jimafisk** [comment]
Sounds like the entrypoint in GitHub actions is not configurable: https://github.community/t/custom-entrypoint-for-container-jobs/18243:

> Using custom entrypoint and startup command for a container job is not supported. 

Since we use a [custom entrypoint](https://github.com/plentico/plenti/blob/f1ff1f1127791910d98c61f94e277af4dc037bb2/Dockerfile#L3) in our Dockerfile, if you `docker pull plentico/plenti:latest` and run locally you get:

`docker run --name plenti-test --entrypoint "tail" plentico/plenti` produces:
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"tail\": executable file not found in $PATH": unknown.
ERRO[0001] error waiting for container: context canceled
```

`docker run --name plenti-test --entrypoint "/plenti" plentico/plenti` produces:
```
standard_init_linux.go:211: exec user process caused "no such file or directory"
```

**Comment by jimafisk** [comment]
It seems that by default the plenti binary can't run with a container based on scratch or alpine. If you ssh into an alpine container (`docker exec -it plenti-test /bin/sh`) and try to execute the binary (`./plenti`) you get something like `/bin/sh: plenti: not found`. If you try to try to execute it from outside the container (`docker exec -it plenti-test /plenti`) you get `OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "no such file or directory": unknown`.

If you instead use a `Dockerfile` based on CentOS for example:
```
FROM centos
COPY plenti /
ENTRYPOINT ["/plenti"]
```

Then inside the plenti source code build a binary (`go build`) and include it in a new image (`docker build -t plenti-local/plenti-local .`)

Then create a container from the image: `docker run -dit --name plenti-test --entrypoint "tail" plenti-local/plenti-local`

Then you can either SSH into the container (`docker exec -it plenti-test /bin/bash`) and run the plenti binary (`/plenti`), or just run the binary from outside the container (`docker exec -it plenti-test /plenti`) and it will successfully print the default plenti help text.

We might be able to get around this on scratch or alpine with the net package: https://stackoverflow.com/questions/36279253/go-compiled-binary-wont-run-in-an-alpine-docker-container-on-ubuntu-host

**Comment by jimafisk** [comment]
I ultimately used `ubuntu` as the base image in order to get the containers to initialize. We should revisit this in the future because downloading a slimmer container will make the build faster, which will be important for the git-cms.

<details>
<summary>If using with GitHub Pages here's an example .github/workflows/gh-pages.yml</summary>

```yml
name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Build
        uses: docker://plentico/plenti:latest
        with:
          entrypoint: /plenti
          args: build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.
```

</details>
