### ISSUE TITLE
GitLab pages

### ISSUE THREAD

**Issue by jimafisk** [plentico/plenti#66]
Adding a `.gitlab-ci.yml` to the project:

```yml
image: plentico/plenti

pages:
  script:
    - plenti build
  artifacts:
    paths:
      - public
  only:
    - master          
```

Results in this error:
```
Executing "step_script" stage of the job script
00:01
Error: unknown command "sh" for "plenti"
Run 'plenti --help' for usage.
unknown command "sh" for "plenti"
ERROR: Job failed: exit code 1
```

It seems you can't use a custom `ENTRYPOINT`: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1501#note_28682187. We're currently doing this on the official dockerhub image: https://github.com/plentico/plenti/blob/4faa4ad25e1709ba3a78498f37990dc848957dfe/Dockerfile#L3

**Comment by jimafisk** [comment]
Setting an empty entrypoint (as suggested [here](https://community.k6.io/t/gitlab-loadimpact-k6-docker-image-unknown-command-sh-for-k6/116/5), [here](https://gitlab.com/gitlab-org/gitlab-foss/-/issues/65110#note_198073241), [here](https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1421#note_366382971) and [here](https://github.com/klakegg/docker-hugo/issues/13#issuecomment-678304121)) and using an absolute path to the binary seems to have worked:

```yml
image:
  name: plentico/plenti:latest
  entrypoint: [""]            

pages:
  script:
    - /plenti build
  artifacts:
    paths:
      - public
  only:
    - master
```
