### ISSUE TITLE
Add GitHub pages and GitLab pages CI instructions to site defaults

### ISSUE THREAD

**Issue by jimafisk** [plentico/plenti#67]
You can set up Plenti to deploy to github pages automatically using a `.github/workflows/gh-pages.yml` file like this: https://github.com/plentico/plenti.co/blob/ea1f3383e24e68f3d57aa60790f771b1f7109577/.github/workflows/gh-pages.yml

<details>
<summary>Click to see example gh-pages.yml</summary>

```yml

name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Build
        uses: docker://plentico/plenti:latest
        with:
          entrypoint: /plenti
          args: build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.
```

</details>

You could do something similar with gitlab pages using a `.gitlab-ci.yml` file:
```yml
image:
  name: plentico/plenti:latest
  entrypoint: [""]            

pages:
  script:
    - /plenti build
  artifacts:
    paths:
      - public
  only:
    - master
```

My plan is to add these as default files that are created when running the `plenti new site my-site` command. That way folks don't have to look these up each time they want to deploy to one of these free hosting services. The files shouldn't conflict with anything if you choose not to use them, the downside I see is that it adds clutter to the default starter. That could be mitigated with a `--bare` flag: https://github.com/plentico/plenti/issues/18
